ototadana/sd-face-editor

scripts/face_editor.py

fix value-error #1

---

scripts/face_editor.py

stop setting the restore_faces option

---

scripts/face_editor.py

Add batch processing function: #7

Add batch processing function

---

scripts/face_editor.py

fix https://github.com/ototadana/sd-face-editor/issues/7#issuecomment-1501376904

fix txt2img for hiresfix

---

scripts/face_editor.py

Fix a bug in combination with controlnet in img2img

---

scripts/face_editor.py

- Added "Save original image" option
- Improved skipping of grid images
- Corrected an error in seed assignment when generating multiple images
- In txt2img, made it possible to use with controlnet

add save original image option

---

scripts/face_editor.py

Reverts ototadana/sd-face-editor#16

Revert "add save original image option"

---

scripts/face_editor.py

- Added "Save original image" option
- Improved skipping of grid images
- Corrected an error in seed assignment when generating multiple images
- In txt2img, made it possible to use with controlnet

Added "Save original image" option

---

scripts/face_editor.py

Fixes that may resolve errors reported in #21

add setting for retinaface.device

---

scripts/face_editor.py

fix retinaface.device settings to run earlier

---

scripts/face_editor.py

fix cuda_init error

---

scripts/face_editor.py

add "Show intermediate steps" option

---

scripts/face_editor.py

fix size of tensor error

---

scripts/face_editor.py

add "Apply inside mask only" option

---

scripts/face_editor.py

fix variation seed setting in batch execution

---

scripts/face_editor.py

make batch size and batch count available on img2img

---

scripts/face_editor.py

fix ValueError: operands could not be broadcast

---

scripts/face_editor.py

fix preview

---

scripts/face_editor.py

for https://github.com/ototadana/sd-face-editor/issues/41#issuecomment-1537340496

add "apply scripts to faces" option

---

scripts/face_editor.py
scripts/face_editor_extension.py

add extension

---

README.md
scripts/face_editor.py
scripts/face_editor_extension.py

fix extension related bugs

---

scripts/face_editor_extension.py

enable API call

---

scripts/face_editor.py
scripts/face_editor_extension.py

fix save button is not working

---

scripts/face_editor.py
scripts/face_editor_extension.py

The following options were added: 
- Size of the face when recreating
-  #65
- Use minimal area for face selection

add "Use minimal area for face selection" option

---

scripts/face_editor.py
scripts/face_editor_extension.py

add information to png

---

README.md
scripts/face_editor.py
scripts/face_editor_extension.py

add ignore larger faces option

---

scripts/face_editor.py

fix errors when running with ControlNet

---

scripts/face_editor.py

Skip image processing when denoising strength is 0

---

scripts/face_editor.py

Added debug info to the "Show intermediate steps" images.

add debug info to the intermediate images

---

scripts/face_editor.py

fix __save_images error

---

scripts/face_editor.py

fix bug when used with webui 1.3.2

---

README.md
scripts/entities/face.py
scripts/entities/option.py
scripts/ui/ui_builder.py
scripts/use_cases/image_processor.py
scripts/use_cases/workflow_manager.py

add upscaler option

---

install.py

fix installation error

---

scripts/ui/ui_builder.py
scripts/use_cases/image_processor.py

add save_original_on_detection_fail option

---

scripts/inferencers/img2img_face_processor.py

fix type hint on img2img face processor

---

scripts/entities/face.py
scripts/entities/rect.py
scripts/inferencers/bisenet_mask_generator.py
scripts/inferencers/debug_processor.py
scripts/inferencers/mediapipe/face_detector.py
scripts/inferencers/retinaface_detector.py
scripts/inferencers/rotate_face_processor.py
scripts/ui/ui_builder.py
scripts/use_cases/image_processing_util.py
scripts/use_cases/image_processor.py
scripts/use_cases/workflow_manager.py

Improve tilted faces

---

scripts/use_cases/image_processor.py

show grid image

---

install.py
scripts/use_cases/query_matcher.py
scripts/use_cases/workflow_manager.py

add attribute query function

---

README.md
scripts/inferencers/README.md
scripts/inferencers/insightface/README.md
scripts/use_cases/workflow_manager.py
workflows/examples/README.md
workflows/examples/blur_young_people.json

fix criteria match

---

README.md
scripts/inferencers/openmmlab/README.md
scripts/inferencers/openmmlab/installer.py
scripts/inferencers/openmmlab/mmseg_mask_generator.py
scripts/inferencers/yolo/README.md
workflows/examples/openmmlab.json

Add mmseg mask generator using Occlusion-aware face segmentation model.
#143

add mmseg mask generator

---

README.md
scripts/ui/ui_builder.py
scripts/use_cases/image_processor.py

Add a setting to make it easier when using SDXL.

add "Auto face size adjustment by model" option

---

scripts/use_cases/image_processor.py

fix LoRA description disappears from PNG Info

---

scripts/use_cases/image_processor.py

fix denoising strength of infotext

---

scripts/inferencers/img2img_face_processor.py

add use_refiner_model_only option to Img2ImgFaceProcessor

---

README.md

add description of sd.next branch to README

---

scripts/inferencers/img2img_face_processor.py

fix use_refiner_model_only error

---

scripts/inferencers/img2img_face_processor.py

fix Hires Fix with a custom checkpoint

---

scripts/inferencers/img2img_face_processor.py

remove unexpected masks
